// 이 파일은 동기화 스크립트에 의해 자동 생성되었습니다.
const CACHED_VIDEOS_TIMESTAMP = 1791008112285;
const CACHED_VIDEOS = [
    {
        "title": "물의 낙차로 어떻게 전기를 만들까? 양수발전소의 원리",
        "videoId": "zcP-rtrYc-k",
        "thumbnail": "https://i.ytimg.com/vi/zcP-rtrYc-k/maxresdefault.jpg",
        "published": "2026-02-02T03:09:21+00:00",
        "views": 176860,
        "channelName": "bRd 3D",
        "channelId": "UCgp715TVX9u6cab9XCsFtTw",
        "channelAvatar": "https://yt3.googleusercontent.com/6nUQmkVjAElrUwF68Xwdq9AIFMQ6U6cGq56zMSC06bnkAHMpHXWO2-VNV5AHvsCCP37lKLX0ZQE=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=zcP-rtrYc-k"
    },
    {
        "title": "How London Looks at Dusk 🇬🇧 Busy West End City Streets Evening Walk 2026 | 4K HDR",
        "videoId": "KPhKLkqHx6Q",
        "thumbnail": "https://i.ytimg.com/vi/KPhKLkqHx6Q/maxresdefault.jpg",
        "published": "2026-10-02T11:00:26+00:00",
        "views": 7066,
        "channelName": "Watched Walker",
        "channelId": "UC_mzz_JnzArhhpGUy8KdGwg",
        "channelAvatar": "https://yt3.googleusercontent.com/yUX1ypGtQ85ZiLwJ5dw8PUo_3KgbJPiiadq-uHYCeT5tg9d8HKJmPtclowkrCdyDHKNyvcbKZg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=KPhKLkqHx6Q"
    },
    {
        "title": "7일 동안 유목민으로 살면 생기는 일",
        "videoId": "-G7ZZmGzInI",
        "thumbnail": "https://i.ytimg.com/vi/-G7ZZmGzInI/maxresdefault.jpg",
        "published": "2026-09-11T09:01:57+00:00",
        "views": 5649940,
        "channelName": "고재영",
        "channelId": "UClWg5n2YST6_697s-zQSMnA",
        "channelAvatar": "https://yt3.googleusercontent.com/KUsRayyFFxnk-gtNKJbBRV7QVLPxikqPCYbOWYUFnTyijeJ5G0z1MQ9v3tWsNb-ybgyogsgu=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=-G7ZZmGzInI"
    },
    {
        "title": "미스터리를 그리는 화가 차혜림",
        "videoId": "fPi5tzfc-CU",
        "thumbnail": "https://i.ytimg.com/vi/fPi5tzfc-CU/maxresdefault.jpg",
        "published": "2026-09-30T11:00:16+00:00",
        "views": 3940,
        "channelName": "Korean Art Story",
        "channelId": "UCWxjiGSVrwU4rbSxEMBIZiA",
        "channelAvatar": "https://yt3.googleusercontent.com/s81WfZlpkJciyDw5h0dWFAT0PR9SM9Paaf16wkErG7HVVvhWX9Ws8V1hnws0BNs6Werbx3dEXg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=fPi5tzfc-CU"
    },
    {
        "title": "[UE5] 언리얼엔진과 미디어파이프를 활용한 인터렉티브 컨텐츠 튜토리얼",
        "videoId": "4ywYDcR8bjM",
        "thumbnail": "https://i.ytimg.com/vi/4ywYDcR8bjM/maxresdefault.jpg",
        "published": "2025-06-07T16:59:31+00:00",
        "views": 9322,
        "channelName": "김랜턴 KimLantern",
        "channelId": "UCOvvWmg_MM1ctt4w5s5cfrg",
        "channelAvatar": "https://yt3.googleusercontent.com/jPbcU2RalvevLX9s_sseiZTk1DgR9EOyCzIqcLJQg495l2fxgLWA7WIhoVSkIN5HvI8CevbDlg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=4ywYDcR8bjM"
    },
    {
        "title": "블루베리, 온도를 낮추니 병까지 줄었다",
        "videoId": "LQcdYg35Lg8",
        "thumbnail": "https://i.ytimg.com/vi/LQcdYg35Lg8/maxresdefault.jpg",
        "published": "2026-10-03T01:00:13+00:00",
        "views": 976,
        "channelName": "Plant Hugs",
        "channelId": "UCmFZ0JAXaKCfPq33K8ASrNQ",
        "channelAvatar": "https://yt3.googleusercontent.com/6UVUqDFfMxuvDFEM_t6a3ArGJE26lbxEs52sgOe_kYVekj42iFGBH4yEExzKNJbPozgL1v-UIA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=LQcdYg35Lg8"
    },
    {
        "title": "[MV] 달빛정원 - 메리크리스마스 투유 | Moonlight Garden - Merry Christmas to you",
        "videoId": "rWXAAc64abg",
        "thumbnail": "https://i.ytimg.com/vi/rWXAAc64abg/maxresdefault.jpg",
        "published": "2022-12-21T16:17:08+00:00",
        "views": 517,
        "channelName": "달빛정원 official",
        "channelId": "UCOj23ekvXa2S93YqX-AFSpw",
        "channelAvatar": "https://yt3.googleusercontent.com/0iiNIayRA48hyIesQtOxZmufXBCME8S9Wd-eCfEBM0GDasASBkDvESbbzdQAp4aa682MxFNjEQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=rWXAAc64abg"
    },
    {
        "title": "이런 세상이 왔다니!!",
        "videoId": "jRJ_kwswqxI",
        "thumbnail": "https://i.ytimg.com/vi/jRJ_kwswqxI/maxresdefault.jpg",
        "published": "2026-09-30T09:14:06+00:00",
        "views": 8483,
        "channelName": "데프콘TV",
        "channelId": "UCb4bVA5kBfTsZCLaN9iJqjQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ngwzxV6ZmEmpDRl3cbTUn1l8hHsa8CfBa5Uxdj2N7u6cxDNBU2sJVyxEOGKM7r2EKYdFhKhKEb8=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=jRJ_kwswqxI"
    },
    {
        "title": "제2회 벌스워크 X 노페어 게임대회 시상식",
        "videoId": "17k-AWc2o2o",
        "thumbnail": "https://i.ytimg.com/vi/17k-AWc2o2o/maxresdefault.jpg",
        "published": "2026-08-29T17:44:30+00:00",
        "views": 1287,
        "channelName": "노페어",
        "channelId": "UCMIyfh-0MQ9qcxF2Fiee8lA",
        "channelAvatar": "https://yt3.googleusercontent.com/QF08J51t8eSa2dBHhEz7-tfBtT5MNIH6q0YWCa4lPax3BiYKQoaV0Q7zOVQQCGrpwmX5wTWd=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=17k-AWc2o2o"
    },
    {
        "title": "AI 3D가 .. 한 단계 더 진화했습니다 I  최종보스 후보등장 I HI3D",
        "videoId": "MaXV3qAMAC8",
        "thumbnail": "https://i.ytimg.com/vi/MaXV3qAMAC8/maxresdefault.jpg",
        "published": "2026-06-12T06:13:45+00:00",
        "views": 1225743,
        "channelName": "LIM_blender",
        "channelId": "UC75_2AqLzrOAYWsEoUHHqyw",
        "channelAvatar": "https://yt3.googleusercontent.com/1cxF4I_CWl-0C1mgdF5YYwsnom3d4XzUbbhyunJ7sCwNtxkA00zovhzT22IuP-nlcuFRWfjFgg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=MaXV3qAMAC8"
    },
    {
        "title": "동양인 한명도 없는 미지의 섬나라 세인트빈센트 그레나딘 #105",
        "videoId": "FPvR0xWhqoY",
        "thumbnail": "https://i.ytimg.com/vi/FPvR0xWhqoY/maxresdefault.jpg",
        "published": "2026-10-03T00:00:16+00:00",
        "views": 83338,
        "channelName": "모칠레로 Mochilero",
        "channelId": "UCUcy82tGagXlj4t1p2todeQ",
        "channelAvatar": "https://yt3.googleusercontent.com/exy_ve5D0k4VDtOxy1Yv8p-N3yns0ys9iVYrQ2A0IR8GzhtiF0Ztd21X0z3ElCOsGAaR2KeRqi0=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=FPvR0xWhqoY"
    },
    {
        "title": "서울메이커페어 2026 스케치 영상 #3d프린터 #이제는일상",
        "videoId": "EVcg3UHeJOo",
        "thumbnail": "https://i.ytimg.com/vi/EVcg3UHeJOo/maxresdefault.jpg",
        "published": "2026-09-19T14:54:06+00:00",
        "views": 652,
        "channelName": "메이커 다은쌤",
        "channelId": "UC-TbOuCyTywTg9G9e_LWAbg",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_nYifclJYD0CVCJTcYp8HCTbehDbuNxNDVXbt-RgNfbkdE=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=EVcg3UHeJOo"
    },
    {
        "title": "소박한 낭만, 미국배당주식 3억 파이어 미니멀라이프",
        "videoId": "Oqu3rsYvinI",
        "thumbnail": "https://i.ytimg.com/vi/Oqu3rsYvinI/maxresdefault.jpg",
        "published": "2026-10-03T02:00:26+00:00",
        "views": 7657,
        "channelName": "배당아저씨",
        "channelId": "UCUS-I9DgdlNrvBOIGUCJthA",
        "channelAvatar": "https://yt3.googleusercontent.com/rTBeIebTE5VUs5P8e3zZYwOzprmTbC7Pne-_UzMEGFprJsxAiPHwtpCh_Bw8P-3M5G4yI7sThQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=Oqu3rsYvinI"
    },
    {
        "title": "바다나들목 라이브 엔딩곡",
        "videoId": "kEmRavoT8_g",
        "thumbnail": "https://i.ytimg.com/vi/kEmRavoT8_g/maxresdefault.jpg",
        "published": "2026-09-30T16:15:42+00:00",
        "views": 1443,
        "channelName": "바다나들목",
        "channelId": "UCojKaejTXbmH4KU_Z9roCKw",
        "channelAvatar": "https://yt3.googleusercontent.com/YheV4JqH7ou0pKrpsYgHLKU9KGVmCoNceIJCu-KsfcCLX6t4jExUlodtU_WTR8qkKFQs5H5DKFk=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=kEmRavoT8_g"
    },
    {
        "title": "대서양이 사막을 삼키고 있다 — 한 번의 홍수로 완전히 새로운 바다가 생길 수 있다",
        "videoId": "nkc39aVs8EA",
        "thumbnail": "https://i.ytimg.com/vi/nkc39aVs8EA/maxresdefault.jpg",
        "published": "2026-10-03T02:07:05+00:00",
        "views": 5055,
        "channelName": "밝은 면 Bright Side Korea",
        "channelId": "UCWklve34yV5A9A69-1sRLBA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kca9AaiMCl9hd2hEX6bAAs6lB7R8Rz5bO7EJA3Y2VOT7E=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=nkc39aVs8EA"
    },
    {
        "title": "세종대왕은 왜 늙은 기생의 춤을 보고 상을 내렸을까? | 부활수업",
        "videoId": "htQMQ6gtGzs",
        "thumbnail": "https://i.ytimg.com/vi/htQMQ6gtGzs/maxresdefault.jpg",
        "published": "2026-09-30T07:00:15+00:00",
        "views": 6825,
        "channelName": "부활수업 Immortal Class",
        "channelId": "UCA52ekar5-V85dHrI6zsFig",
        "channelAvatar": "https://yt3.googleusercontent.com/fYsKnueeL0wnBo29BEoqUTt1jbcdzgzMYj228WqilOrtOp9qxj6AJdPsgoAw3lvu6IjkUiZx=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=htQMQ6gtGzs"
    },
    {
        "title": "집 나갔던 예술혼을 자극하는 영감 노트",
        "videoId": "3ilLQXkPIxE",
        "thumbnail": "https://i.ytimg.com/vi/3ilLQXkPIxE/maxresdefault.jpg",
        "published": "2026-09-06T03:00:04+00:00",
        "views": 122561,
        "channelName": "블랙스완",
        "channelId": "UCtd9j7UUM668BxTZQ0s6-LA",
        "channelAvatar": "https://yt3.googleusercontent.com/M8iNf2xy_0uIewknt7Rsm2bdq4vmdzCIrR7dAX-qhtM6GwaL-Q_2w-r0RPsWnxfNqlB0TJhDQg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=3ilLQXkPIxE"
    },
    {
        "title": "[국민기자단]🎥 청년의 날 기념 2030청년자문단 정책 교류 세미나 현장은?",
        "videoId": "ugfFRbj17FA",
        "thumbnail": "https://i.ytimg.com/vi/ugfFRbj17FA/maxresdefault.jpg",
        "published": "2026-10-02T06:44:43+00:00",
        "views": 511,
        "channelName": "법무부TV",
        "channelId": "UCv98wlLoiNXta0k34cy0zvA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lw4s5CAj_QazQphSN3h71z5yxnMvKYIcYYtAeczPutHKg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=ugfFRbj17FA"
    },
    {
        "title": "칫솔 만들기",
        "videoId": "S8LdzkGRwx8",
        "thumbnail": "https://i.ytimg.com/vi/S8LdzkGRwx8/maxresdefault.jpg",
        "published": "2026-10-01T09:00:12+00:00",
        "views": 561316,
        "channelName": "3D SANAGO",
        "channelId": "UCd4FmcWIVdWAy0-Q8OJBloQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_nN-7Vdy0T2PEWo5palhhFWXuNaDYqGDlLYX_FR-96qbmQa=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=S8LdzkGRwx8"
    },
    {
        "title": "\"엔비디아 부진해도 삼전은 올라갈 것\" 어떻게 되길래?ㅣ노근창 세미콘리서치랩 대표 [주말인터뷰]",
        "videoId": "Pk0vZoWct7U",
        "thumbnail": "https://i.ytimg.com/vi/Pk0vZoWct7U/maxresdefault.jpg",
        "published": "2026-10-03T06:00:06+00:00",
        "views": 1023,
        "channelName": "삼프로TV 3PROTV",
        "channelId": "UChlv4GSd7OQl3js-jkLOnFA",
        "channelAvatar": "https://yt3.googleusercontent.com/--qajlNgqpwDCjcupwfYwXsgXS3szfhMEEFGI1ouLTj4CKOtwGOyXGR7xl8-tzOGCDFt9umfqQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=Pk0vZoWct7U"
    },
    {
        "title": "더클래스 CLINITY - 가죽과 패브릭 관리 편",
        "videoId": "lq0-5_bRK9A",
        "thumbnail": "https://i.ytimg.com/vi/lq0-5_bRK9A/maxresdefault.jpg",
        "published": "2026-09-24T00:00:11+00:00",
        "views": 48,
        "channelName": "상구의 일상 리뷰",
        "channelId": "UCZZHfWxkF40wBOmulH17X6w",
        "channelAvatar": "https://yt3.googleusercontent.com/6fged72-cDJHr76HXYH-jv8ntbwlCUZ4cS9oS4znYcIsThuknoWsxCL2TCyChnx6xbCoM3u3Wg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=lq0-5_bRK9A"
    },
    {
        "title": "무모하리만큼 도전하라! 1세대 피겨스케이팅 선수 출신 85학번 선배 인터뷰|[서울여대학보 디지털뉴스부 기획]",
        "videoId": "XTQ4hzGLhrc",
        "thumbnail": "https://i.ytimg.com/vi/XTQ4hzGLhrc/maxresdefault.jpg",
        "published": "2022-07-03T06:00:44+00:00",
        "views": 316,
        "channelName": "서울여대학보",
        "channelId": "UCiizyjE-CALK827rl1T0uRA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_mQsuc8JEFtq-2vebNWY3cLv2qVKzL13ZmUwLW3-7zXFw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=XTQ4hzGLhrc"
    },
    {
        "title": "동네 배드민턴장 텃세",
        "videoId": "ZMR8fl-11Q8",
        "thumbnail": "https://i.ytimg.com/vi/ZMR8fl-11Q8/maxresdefault.jpg",
        "published": "2026-10-03T03:00:13+00:00",
        "views": 1021,
        "channelName": "세바시 강연 Sebasi Talk",
        "channelId": "UCgheNMc3gGHLsT-RISdCzDQ",
        "channelAvatar": "https://yt3.googleusercontent.com/r7kVqIDUDyGQvmbOdi1GNAahUHaHPZl8Z92gSfSlWSdQOEr2kFgSsQQhAzUHvRxfYdTAasLatA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=ZMR8fl-11Q8"
    },
    {
        "title": "자유형 호흡 어떻게 하면 잘 할수 있을까 많은 고민과 경험의 노하우를 공개 합니다 2편",
        "videoId": "MQiw6C_bsZ0",
        "thumbnail": "https://i.ytimg.com/vi/MQiw6C_bsZ0/maxresdefault.jpg",
        "published": "2023-04-22T23:00:06+00:00",
        "views": 2601067,
        "channelName": "Standard of swimming",
        "channelId": "UCzWvQMJbcRoOjpHzOLF6W1Q",
        "channelAvatar": "https://yt3.googleusercontent.com/hTcYDghqqbNVEYVWYubNQ3wFrLZk9ibY1-qeheUKzEZyCyuG3uLvSaKSbjuCWfY8r1Ac_Z2a=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=MQiw6C_bsZ0"
    },
    {
        "title": "벤딕트 실버 라이닝 퓨어 프로 무선 청소기 실사 리뷰 | 150W 흡입력에 7,500mAh 배터리, 차량용으로도 최고",
        "videoId": "W8CIo5-cZfI",
        "thumbnail": "https://i.ytimg.com/vi/W8CIo5-cZfI/maxresdefault.jpg",
        "published": "2026-08-21T02:04:46+00:00",
        "views": 658,
        "channelName": "순순한리뷰",
        "channelId": "UC4imJj8mEk7RfkI9myqYbBA",
        "channelAvatar": "https://yt3.googleusercontent.com/VxJgE10TQlGB2i5SVPe1RNpXGH4b46e8aq7WFmT8I73AzuTgssIxEGW9t8h22JTKRp0wWx_j=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=W8CIo5-cZfI"
    },
    {
        "title": "Respect",
        "videoId": "hNco4CbATVE",
        "thumbnail": "https://i.ytimg.com/vi/hNco4CbATVE/maxresdefault.jpg",
        "published": "2025-11-07T09:31:28+00:00",
        "views": 2926219,
        "channelName": "스토리",
        "channelId": "UCm2PiWccs-otbzhjiNXHu5g",
        "channelAvatar": "https://yt3.googleusercontent.com/ArBE4TRbn2hcjtgT8OCJpEPFG6mMOb7dI_SlP7UYBfjol6LdM3o3_nx2tB6DtiviRTgrQBL9FQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=hNco4CbATVE"
    },
    {
        "title": "서울 수도박물관 마당 밑에 정수장이 있습니다  서울 첫 수돗물은 모래로 걸렀거든요",
        "videoId": "8g6ILQD4l4E",
        "thumbnail": "https://i.ytimg.com/vi/8g6ILQD4l4E/maxresdefault.jpg",
        "published": "2026-10-03T06:00:07+00:00",
        "views": 227,
        "channelName": "신비한 건축사전",
        "channelId": "UCeEM8XgdgUyaWE1Z6_5sHbQ",
        "channelAvatar": "https://yt3.googleusercontent.com/WRoc-KHxWY3OJ9RQv5_to2BYqzFP-OoeQZ3d0C1dPkCF-Dr0KtauerxyjxHsfExv7x-CSCSz2w=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=8g6ILQD4l4E"
    },
    {
        "title": "‘부캉이’에게 물을 뿌린 진짜 이유?!",
        "videoId": "3ETM1Dlv0pQ",
        "thumbnail": "https://i.ytimg.com/vi/3ETM1Dlv0pQ/maxresdefault.jpg",
        "published": "2026-10-03T02:00:16+00:00",
        "views": 3533,
        "channelName": "안될과학 Unrealscience",
        "channelId": "UCMc4EmuDxnHPc6pgGW-QWvQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_mfJU2V3f_mAORcKfyq-z7dPujl4aisAWyAQ9bJVeUDLw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=3ETM1Dlv0pQ"
    },
    {
        "title": "AI에게 3ds Max 모델링부터 언랩·베이크·텍스처링까지 시켜봤습니다",
        "videoId": "4ELN93ui84w",
        "thumbnail": "https://i.ytimg.com/vi/4ELN93ui84w/maxresdefault.jpg",
        "published": "2026-09-25T03:10:24+00:00",
        "views": 32253,
        "channelName": "안콜3D",
        "channelId": "UC63C3GOhuFz1yJPOavscPCw",
        "channelAvatar": "https://yt3.googleusercontent.com/OUnuPqR1cBw9vRy-_ThtjFxlrYTYntFoVUxs_O8yWE7Ug7uh32_6OZZmBuED9gg9J2PNtBwvaQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=4ELN93ui84w"
    },
    {
        "title": "제작비 5천만원짜리 퀄리티 광고, 50만원에 나왔습니다.",
        "videoId": "IB5Q_BfGc2I",
        "thumbnail": "https://i.ytimg.com/vi/IB5Q_BfGc2I/maxresdefault.jpg",
        "published": "2026-09-21T09:15:03+00:00",
        "views": 16557,
        "channelName": "WENSON",
        "channelId": "UC4AVc-iIPWIDl6TTi92TS2Q",
        "channelAvatar": "https://yt3.googleusercontent.com/WI0xvhV9QA_eIPCH5WllsXf9JcF2u-bzjHRVOyax9MYHXIYMX849VKBLdh0So6fx8tNlC1i0=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=IB5Q_BfGc2I"
    },
    {
        "title": "Youtube 치지직 API 연동 테스트",
        "videoId": "QBpxmwvxfUs",
        "thumbnail": "https://i.ytimg.com/vi/QBpxmwvxfUs/maxresdefault.jpg",
        "published": "2025-10-11T18:30:19+00:00",
        "views": 443,
        "channelName": "윤농 Yunnong",
        "channelId": "UCFzoKNDfvq7YyyAGqp9iHZA",
        "channelAvatar": "https://yt3.googleusercontent.com/Y6mlBVc5G1KVLQNfufAleGyLPfgA_ExQxXbROWdH2M788sdOhS2OPy7XvRVUvAsxs72GK5tumQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=QBpxmwvxfUs"
    },
    {
        "title": "돈 주고도 못 사는 법인 '업력' 알박기 꿀팁",
        "videoId": "F1hR_5b5e70",
        "thumbnail": "https://i.ytimg.com/vi/F1hR_5b5e70/maxresdefault.jpg",
        "published": "2026-10-01T23:30:02+00:00",
        "views": 1956,
        "channelName": "장래희망:아빠",
        "channelId": "UC91U9srdcS-CqA6dWkX5KbA",
        "channelAvatar": "https://yt3.googleusercontent.com/NovdgqbTmItEUSehKG3cMNEMdRBE_wNkBpNb7N84XWCg5wZgRwmRXv5Zxhyn0FDlWAVSJZ4s=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=F1hR_5b5e70"
    },
    {
        "title": "10/3 과천 중앙선관위 ~ 올공!!",
        "videoId": "B0kse3Y38Fo",
        "thumbnail": "https://i.ytimg.com/vi/B0kse3Y38Fo/maxresdefault.jpg",
        "published": "2026-10-02T23:02:36+00:00",
        "views": 26881,
        "channelName": "자영업의 모든것",
        "channelId": "UC-i29uxJTqD7xOWZJ-9lEQw",
        "channelAvatar": "https://yt3.googleusercontent.com/w_otsr3pq3C4rNB8DoFU-u-mnYaNZfpilKxh7mpoQI5RuDfFuC2iMdilSIYDxHSELNCBM5OGKQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=B0kse3Y38Fo"
    }
];
