// 이 파일은 동기화 스크립트에 의해 자동 생성되었습니다.
const CACHED_VIDEOS_TIMESTAMP = 1790921421305;
const CACHED_VIDEOS = [
    {
        "title": "당신이 아직 모르는 C++ 게임 엔진",
        "videoId": "HTzPaBxvKfk",
        "thumbnail": "https://i.ytimg.com/vi/HTzPaBxvKfk/maxresdefault.jpg",
        "published": "2024-08-07T05:19:29+00:00",
        "views": 7109,
        "channelName": "bingsoo",
        "channelId": "UCziegKt_CGZW3GoyDjCXTaQ",
        "channelAvatar": "https://yt3.googleusercontent.com/D2tPuo7M8yEJTLNz2CljPtw8ahvxVXfJ-lcYYrATdvRFH24-GGyFyhWzDeRiNmp2VngnFNwF=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=HTzPaBxvKfk"
    },
    {
        "title": "프로그래밍 패턴 | 템플릿 메서드 (Template Method Pattern) C++로 이해하기",
        "videoId": "K0Ry_wRU_kI",
        "thumbnail": "https://i.ytimg.com/vi/K0Ry_wRU_kI/maxresdefault.jpg",
        "published": "2026-09-30T01:26:28+00:00",
        "views": 78,
        "channelName": "1인개발TV",
        "channelId": "UCDkuAC7cOfEuYgcAuSW_OHg",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kxTyFPNUIkI0vOS11InsGOKeWARwKTVUpfrqfhaILXPwQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=K0Ry_wRU_kI"
    },
    {
        "title": "GAUSSIAN SPLATS, DLSS, Outliner, and more! - Blender Today LIVE #290",
        "videoId": "x3znZU4YUME",
        "thumbnail": "https://i.ytimg.com/vi/x3znZU4YUME/maxresdefault.jpg",
        "published": "2026-09-30T17:05:08+00:00",
        "views": 21916,
        "channelName": "Blender",
        "channelId": "UCSMOQeBJ2RAnuFungnQOxLg",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_nqhez5E1j4YzrCvzTAAB6z_KDFFZznqWv0x-vfY2gsXdY=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=x3znZU4YUME"
    },
    {
        "title": "시뮬레이션이 중요한 이유 #shorts",
        "videoId": "GhsJcRysRc0",
        "thumbnail": "https://i.ytimg.com/vi/GhsJcRysRc0/maxresdefault.jpg",
        "published": "2026-10-02T04:00:05+00:00",
        "views": 1607,
        "channelName": "14F 일사에프",
        "channelId": "UCLKuglhGlMmDteQKoniENIQ",
        "channelAvatar": "https://yt3.googleusercontent.com/v_nxcQoJZh_AofyziHgvoC10BNOmdRWhEmiSWCvPZtXtcdPg5NK9kOxno4Q_kIaaWIH-k8LCXA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=GhsJcRysRc0"
    },
    {
        "title": "블렌더3D- 모션젠(MotionGen) 애드온, 비디오 기반 리깅 애니메이션 솔루션",
        "videoId": "myh3WL-zhzU",
        "thumbnail": "https://i.ytimg.com/vi/myh3WL-zhzU/maxresdefault.jpg",
        "published": "2026-07-11T10:02:57+00:00",
        "views": 7669,
        "channelName": "ArTech",
        "channelId": "UCYMG6ButVUpNPl1u8bF-YvQ",
        "channelAvatar": "https://yt3.googleusercontent.com/FOTY9H0jTND4nh2QOuV7SjRX7fkgvtHjZGjtrVKntunrLahN7M_9z7q3Tr8XPrUHtxLTR4cZhA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=myh3WL-zhzU"
    },
    {
        "title": "새끼 쓰다듬도록 허락해 준 비비",
        "videoId": "bQVI2_07C2s",
        "thumbnail": "https://i.ytimg.com/vi/bQVI2_07C2s/maxresdefault.jpg",
        "published": "2026-09-29T02:00:03+00:00",
        "views": 69216,
        "channelName": "ChooChoo's Story",
        "channelId": "UCs2Xfykq6ONapqI6TFKNyOg",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_nnhb5jAmAwIWHN118ceI4pFl6kCz8rZP4drl8xDRKeuw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=bQVI2_07C2s"
    },
    {
        "title": "I grew a cactus from seed and filmed it for 3 years",
        "videoId": "NNjPWqHk68A",
        "thumbnail": "https://i.ytimg.com/vi/NNjPWqHk68A/maxresdefault.jpg",
        "published": "2026-08-13T12:31:54+00:00",
        "views": 132283,
        "channelName": "Boxlapse",
        "channelId": "UCiL9l2J57t5OG2aZ0huswZw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kZGyALurduUnRhFkN4WnFirgAHb3XofedQ0kWfZfGLn-U=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=NNjPWqHk68A"
    },
    {
        "title": "Lilian Zhao - To Assume the Flesh (2024)",
        "videoId": "NAcd27MFcfw",
        "thumbnail": "https://i.ytimg.com/vi/NAcd27MFcfw/maxresdefault.jpg",
        "published": "2025-04-01T14:30:32+00:00",
        "views": 63,
        "channelName": "Electronic and Time-Based Art Purdue University",
        "channelId": "UCpRduIvkIUO3YgaESyjpokw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kvyffoHVJGpAdHWYYijdTV8NX8BORyYMx0RIe48_1qzw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=NAcd27MFcfw"
    },
    {
        "title": "Maya 버텍스 순서 재정렬 (How to Reorder vertices in Maya)",
        "videoId": "ENd_n3mf13s",
        "thumbnail": "https://i.ytimg.com/vi/ENd_n3mf13s/maxresdefault.jpg",
        "published": "2026-08-31T05:19:40+00:00",
        "views": 715,
        "channelName": "First Maya",
        "channelId": "UCH-9sNpbxC2myrckQHIYQPg",
        "channelAvatar": "https://yt3.googleusercontent.com/aodrvxYarWXiv18abLJ8rDOFfGSiKsstFyR27-22FVIXNARnRrCJ36DrsaXrlsQuVE787BRX5A=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=ENd_n3mf13s"
    },
    {
        "title": "신나게 JaeYun #효리수 #skibidi #커버댄스",
        "videoId": "s_CbpLa5sy0",
        "thumbnail": "https://i.ytimg.com/vi/s_CbpLa5sy0/maxresdefault.jpg",
        "published": "2026-09-23T09:38:42+00:00",
        "views": 195,
        "channelName": "AlgoRhythm",
        "channelId": "UC9Y5pxUJgENxqHB8ISspF-g",
        "channelAvatar": "https://yt3.googleusercontent.com/gE4qGBxW_XOO0CvMncgMuDijiKv_4Y2Ucvk72AzorURi5KYqeB5Qz11vgcJs5Hazgranu2nDgA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=s_CbpLa5sy0"
    },
    {
        "title": "From deepfakes to DNA: the science of watermarking AI",
        "videoId": "HIUzrxQxTtw",
        "thumbnail": "https://i.ytimg.com/vi/HIUzrxQxTtw/maxresdefault.jpg",
        "published": "2026-10-01T16:37:46+00:00",
        "views": 14945,
        "channelName": "Google DeepMind",
        "channelId": "UCP7jMXSY2xbc3KCAE0MHQ-A",
        "channelAvatar": "https://yt3.googleusercontent.com/xofhdRNoyqgAB_YpJgAQeasGtE6gTEXpR2v1vyMmtqlRCmoEUIsTGJcavUORLhhKQk3b9UeUFw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=HIUzrxQxTtw"
    },
    {
        "title": "드론 구매하고 후회하지 말고 영상 먼저 보고 구매하세요! | 2026 드론 구매 가이드",
        "videoId": "rhQaVOs5iYM",
        "thumbnail": "https://i.ytimg.com/vi/rhQaVOs5iYM/maxresdefault.jpg",
        "published": "2026-09-19T11:00:11+00:00",
        "views": 25280,
        "channelName": "HarangDrone하랑드론",
        "channelId": "UCzAbjMkktS9x2EcdLyM4zTQ",
        "channelAvatar": "https://yt3.googleusercontent.com/hIwaUHQAzmSW6yrCH5cvkpSag8OOXsouzTRi35Mhw97OrEpCMJ447EuD3whKxBDzNSoeEl2U=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=rhQaVOs5iYM"
    },
    {
        "title": "배꼽과 흰우유",
        "videoId": "k5Map_ENbAQ",
        "thumbnail": "https://i.ytimg.com/vi/k5Map_ENbAQ/maxresdefault.jpg",
        "published": "2026-08-06T13:42:58+00:00",
        "views": 99564,
        "channelName": "HOZZAA2",
        "channelId": "UCv-3DJsuP0DBjQyknHaxncg",
        "channelAvatar": "https://yt3.googleusercontent.com/ykkkyJXy6iiY19K8DEmYaJLWWil4wQHDFTFKyk7EL_DfYbc88jDOxp3GWb9Ho8Qb84WFv68N=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=k5Map_ENbAQ"
    },
    {
        "title": "Why Memory Prices Are Crazy High",
        "videoId": "p8UurM1wvvM",
        "thumbnail": "https://i.ytimg.com/vi/p8UurM1wvvM/maxresdefault.jpg",
        "published": "2026-09-30T13:46:28+00:00",
        "views": 568933,
        "channelName": "HTX Studio",
        "channelId": "UCwffSP9kO8pMZVr1Ugqvbzw",
        "channelAvatar": "https://yt3.googleusercontent.com/oZp4RCNcpuKIx01_-zjE7c07oeWXZgzogMhGunX-mILRW27xgN8xKKjo4UVTAmAtdB0-PpsN8g=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=p8UurM1wvvM"
    },
    {
        "title": "Sagar Kharecha #MyFilmStory - BeautifulIy Imperfect Images",
        "videoId": "CnR-k1Yo4UY",
        "thumbnail": "https://i.ytimg.com/vi/CnR-k1Yo4UY/maxresdefault.jpg",
        "published": "2026-07-27T14:55:06+00:00",
        "views": 8192,
        "channelName": "ILFORD Photo",
        "channelId": "UCMYTOWED2RUuRD1QWVcbdiw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_mB_bz_sqSk1KcdJS5YqrZAf68SCPxU0TAy_3z7m7JQMC4=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=CnR-k1Yo4UY"
    },
    {
        "title": "2D도 삼켜버린 AI 모션그래픽 타이틀 'Maestro'",
        "videoId": "AwSoj0jMFVI",
        "thumbnail": "https://i.ytimg.com/vi/AwSoj0jMFVI/maxresdefault.jpg",
        "published": "2026-10-01T06:00:26+00:00",
        "views": 13612,
        "channelName": "JohnKOBA Design",
        "channelId": "UCYpD5IVQK9BjA2qtupHFExA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lRBrSG2ZtxvDml9W0CJC18LHp21IurqzPTu-weck8rzw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=AwSoj0jMFVI"
    },
    {
        "title": "YE & Don Toliver - OK",
        "videoId": "kSx7OL5-w2E",
        "thumbnail": "https://i.ytimg.com/vi/kSx7OL5-w2E/maxresdefault.jpg",
        "published": "2026-08-18T19:00:06+00:00",
        "views": 5481441,
        "channelName": "Kanye West",
        "channelId": "UCs6eXM7s8Vl5WcECcRHc2qQ",
        "channelAvatar": "https://yt3.googleusercontent.com/jh05JitmhiTaAuBp7AAtTETeO3Zl7bDa-KwcSnZYymMpNF984oQ4k3ZQq1KBPhoKOXHS8B761WM=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=kSx7OL5-w2E"
    },
    {
        "title": "[K Car x KARINA] 세상에 없던 중고차 안심직거래 | 사랑받은 차가 사랑받을 차가 되도록, 직영 중고차에서 안심직거래까지 | 대한민국 No.1 직영 중고차플랫폼 케이카",
        "videoId": "o11doXR6mHU",
        "thumbnail": "https://i.ytimg.com/vi/o11doXR6mHU/maxresdefault.jpg",
        "published": "2026-07-10T15:00:12+00:00",
        "views": 3761,
        "channelName": "K Car -  케이카 공식 유튜브",
        "channelId": "UCp5i9yE8cMxVMOAj5sw3cgA",
        "channelAvatar": "https://yt3.googleusercontent.com/IJyxMEQqdVUaYy0hUISEZ2QUKMSVgjrZCT9_eMA0-ywgTYWVzieOne87OiEz0tFkLMU3NkhO=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=o11doXR6mHU"
    },
    {
        "title": "[이토록 친밀한 배신자] 뭘 하면서 사느냐 보다, 누구와 같이 시간을 보내는 지가 더 중요한 법 ⌚ 함께 해서 깊은 의미였던 VFX 메이킹 MAKING",
        "videoId": "BN2kkcg6PiY",
        "thumbnail": "https://i.ytimg.com/vi/BN2kkcg6PiY/maxresdefault.jpg",
        "published": "2025-05-16T10:00:17+00:00",
        "views": 865,
        "channelName": "MBC 디자인센터",
        "channelId": "UCUT-EIIZNSsON5UE2l24VJw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_mH9Sd8i0liWaQoytdUVCTJFui0KOA57ddG4PjACX0ICg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=BN2kkcg6PiY"
    },
    {
        "title": "거북이는 의외로 빨리 헤엄친다 Title Sequence",
        "videoId": "4E1xex12V84",
        "thumbnail": "https://i.ytimg.com/vi/4E1xex12V84/maxresdefault.jpg",
        "published": "2026-10-02T03:54:21+00:00",
        "views": 61,
        "channelName": "motionlab MG25 (motionlab)",
        "channelId": "UC6irl2z_U4UogX9xn75AE-g",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_njw7jPJNI1RPg8f6Qc0uxxqY5vN99I_Zu-bh1-Q1r9Rg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=4E1xex12V84"
    },
    {
        "title": "넬(NELL) - All This Fxxking Time @경희대 가을대동제 2026",
        "videoId": "6N0cAHKkDAI",
        "thumbnail": "https://i.ytimg.com/vi/6N0cAHKkDAI/maxresdefault.jpg",
        "published": "2026-09-21T09:00:29+00:00",
        "views": 9828,
        "channelName": "OFFICIAL_NELL",
        "channelId": "UChIKGx60x4D5elEbb5Vjtow",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_mZNm4sicFXNOztylbEM4Rf1hPEJKZEOK2-YnTQLeqCMjQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=6N0cAHKkDAI"
    },
    {
        "title": "⚠️WARNING: The Quaya Stream is approaching Earth.⚠️",
        "videoId": "KnHu04YmURA",
        "thumbnail": "https://i.ytimg.com/vi/KnHu04YmURA/maxresdefault.jpg",
        "published": "2026-08-06T01:01:21+00:00",
        "views": 736708,
        "channelName": "NC Official",
        "channelId": "UCbiqc9mdIz3XEH6LG5nCeMg",
        "channelAvatar": "https://yt3.googleusercontent.com/ffu9vkjb48Gou9I2_O_MfifW1k3p7tEygsBKKBTJfeacYe7Sbp10C8QhpR95gBKtx_2x9FSBMbo=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=KnHu04YmURA"
    },
    {
        "title": "Welcoming the start of autumn",
        "videoId": "Pfe7nwcvKTU",
        "thumbnail": "https://i.ytimg.com/vi/Pfe7nwcvKTU/maxresdefault.jpg",
        "published": "2026-10-01T07:22:47+00:00",
        "views": 41,
        "channelName": "Paradise City",
        "channelId": "UCvDMK8zCVbydnwARDFKa9fQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lTngklk57WXjRay7SrIPYZXuNc2iLblFchXXBDFQO_EA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=Pfe7nwcvKTU"
    },
    {
        "title": "Automatic Reference Planes and THP in Qlone Dental",
        "videoId": "YPPU4mE9fyo",
        "thumbnail": "https://i.ytimg.com/vi/YPPU4mE9fyo/maxresdefault.jpg",
        "published": "2026-05-07T15:17:04+00:00",
        "views": 1843,
        "channelName": "Qlone",
        "channelId": "UCkbaZM9rgR1hWkJBoQnwieg",
        "channelAvatar": "https://yt3.googleusercontent.com/P3TDKPwbDW1bzCN_e3bu3y4keCXCz5jC3_HR6OwaXFtdhJYoOBVI2VC5Z1aV1HG0WfDIchej=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=YPPU4mE9fyo"
    },
    {
        "title": "Introducing Continuum: A Real-Time Video Operating System | Runway Labs",
        "videoId": "K7Q7FESRHJY",
        "thumbnail": "https://i.ytimg.com/vi/K7Q7FESRHJY/maxresdefault.jpg",
        "published": "2026-10-01T15:45:30+00:00",
        "views": 30061,
        "channelName": "Runway",
        "channelId": "UCUBqu_z5uP0AZhYtuyFZB3g",
        "channelAvatar": "https://yt3.googleusercontent.com/8rii4_E859zg6NzZAeJId6j2Worzbc8R-RY4as2OCZzHuP_RZPZssOZTHe3dvFx8gj2_TCfEBw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=K7Q7FESRHJY"
    },
    {
        "title": "[Q&A] 10만 구독자 기념 Q&A in 코스타리카",
        "videoId": "n6kFtt981O8",
        "thumbnail": "https://i.ytimg.com/vi/n6kFtt981O8/maxresdefault.jpg",
        "published": "2026-09-14T00:51:31+00:00",
        "views": 8460,
        "channelName": "Skim On West",
        "channelId": "UCHB3rzoUYi0_ArFvb__nRDQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kDTsLsNpv7-VsPCs-wkjz3ubA_1usA8PgE2G659aig_Q=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=n6kFtt981O8"
    },
    {
        "title": "수익화 특집! IAP 와 Ads - 유니티 라이브 2026.09",
        "videoId": "BYbmwN5m8qM",
        "thumbnail": "https://i.ytimg.com/vi/BYbmwN5m8qM/maxresdefault.jpg",
        "published": "2026-09-30T20:37:55+00:00",
        "views": 2445,
        "channelName": "Unity Korea",
        "channelId": "UCQArZVLg7Omzg4cBReJTS3w",
        "channelAvatar": "https://yt3.googleusercontent.com/2GbJoy1rf88ByUwmy1Kc05BcnxH33wbjAxRdqg2n6_VSoZsKTbVKrvPs3zivavdHbuTIC5iV=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=BYbmwN5m8qM"
    },
    {
        "title": "[2025 SEOUL ADEX] AI 에이전트 기반 차세대 IETM(전자교범) & XR기반 지휘통제(C4l) 가시화 시스템 현장 메이킹",
        "videoId": "WaNAwTIIWW4",
        "thumbnail": "https://i.ytimg.com/vi/WaNAwTIIWW4/maxresdefault.jpg",
        "published": "2026-03-03T03:53:30+00:00",
        "views": 231,
        "channelName": "VIVESTUDIOS",
        "channelId": "UC6IO0TgiIfPWjc8nmzm0ofA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_mU8pgdVuf4PTXTnI00pMkEx1qiLrADcI-nzLRy7N5_myc=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=WaNAwTIIWW4"
    },
    {
        "title": "Word STRESS in Arusha Jan 2025",
        "videoId": "yPNhvbhXP_o",
        "thumbnail": "https://i.ytimg.com/vi/yPNhvbhXP_o/maxresdefault.jpg",
        "published": "2024-11-13T06:32:39+00:00",
        "views": 38,
        "channelName": "Thompson Language Center",
        "channelId": "UCpHjr0eZDTwfhGRV8rXUi3Q",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_mtn9fURqTZryMmp2dUOmxETX_3B5F_eM_DgGL9aE2n2mE=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=yPNhvbhXP_o"
    },
    {
        "title": "25.9.11 A drawing for 7h25m20s",
        "videoId": "Ueh25l4Tgkc",
        "thumbnail": "https://i.ytimg.com/vi/Ueh25l4Tgkc/maxresdefault.jpg",
        "published": "2026-09-19T07:32:43+00:00",
        "views": 14,
        "channelName": "YunJung C",
        "channelId": "UC3yr2bagKv5-NtV9vawSvsA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kneY-bi0bJKqNY0-E6E69YVph1lmLdW4KcpCnLeC7P6OeCu0cm50eTRv4gGnhAUKIjMw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=Ueh25l4Tgkc"
    },
    {
        "title": "Museum AI chatbot using Wintor Online Guides",
        "videoId": "YTkVPQHUSFs",
        "thumbnail": "https://i.ytimg.com/vi/YTkVPQHUSFs/maxresdefault.jpg",
        "published": "2024-10-15T11:13:19+00:00",
        "views": 96,
        "channelName": "Wintor AR tour",
        "channelId": "UCTCRL4vF0jvUjRHipx5XOKg",
        "channelAvatar": "https://yt3.googleusercontent.com/nP-0vw6wYUBp7jq-s4QRGAwz5oEEJ759zADiWwm3bCNW_BcW81jmIw4IufakUN4VJ46yDPOE4Q=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=YTkVPQHUSFs"
    },
    {
        "title": "Krey | The China 🇨🇳 Nations Week (2/7) | Vol. 02",
        "videoId": "H0B1_kqHLSM",
        "thumbnail": "https://i.ytimg.com/vi/H0B1_kqHLSM/maxresdefault.jpg",
        "published": "2026-10-01T14:00:27+00:00",
        "views": 4790,
        "channelName": "Swissbeatbox",
        "channelId": "UCzgUc_EaBp2-u-zEvTC6P0g",
        "channelAvatar": "https://yt3.googleusercontent.com/KZ7Nl0AhRYeVA7qbGY6kc2U5vmgldvResKqWc8QNrNgcJD_YG98j3pcsfWkS6YPqjjA4D0-m=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=H0B1_kqHLSM"
    },
    {
        "title": "9955",
        "videoId": "mzRNvCqBPwI",
        "thumbnail": "https://i.ytimg.com/vi/mzRNvCqBPwI/maxresdefault.jpg",
        "published": "2022-06-29T06:41:56+00:00",
        "views": 11127,
        "channelName": "GORANI::Making figures",
        "channelId": "UCClAJKLNW5SV4r6rnL9YfoA",
        "channelAvatar": "https://yt3.googleusercontent.com/NdXQG24y5wdayBNazOx7jxIQ-Ws8zLvryOT83HIw95HVn89AYK3GvrIwQOBdXL7HjPLI_CBV=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=mzRNvCqBPwI"
    },
    {
        "title": "AI가 만들어준 이미지나 기획에 내 기획을 맞추지 마세요",
        "videoId": "bbhJL9mZUS4",
        "thumbnail": "https://i.ytimg.com/vi/bbhJL9mZUS4/maxresdefault.jpg",
        "published": "2026-10-02T05:00:13+00:00",
        "views": 189,
        "channelName": "게임캔버스-게임기획개발아카데미",
        "channelId": "UCZ8xMlkBXBt5NKR62s2tDdw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lewiHaNwh7AzUrl2fJKH0c9B47BX944tzB6qsSuLbq_Ww=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=bbhJL9mZUS4"
    },
    {
        "title": "터치스크린 휴대용 듀얼모니터 이홈웨이 X2 Pro 16인치 듀얼스크린",
        "videoId": "upAOaRJ3Yx0",
        "thumbnail": "https://i.ytimg.com/vi/upAOaRJ3Yx0/maxresdefault.jpg",
        "published": "2024-03-08T01:00:21+00:00",
        "views": 24250,
        "channelName": "곰세 iT",
        "channelId": "UCZVH1Hm_nh9HUTn8GhJlTmA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lhOSKDCHqvAKFxQ34rOobogHUDS3l_CU_NryIQoPo7E8o=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=upAOaRJ3Yx0"
    },
    {
        "title": "How to make an efficient insulation panel",
        "videoId": "fq-QAU_7Uek",
        "thumbnail": "https://i.ytimg.com/vi/fq-QAU_7Uek/maxresdefault.jpg",
        "published": "2024-09-03T14:50:00+00:00",
        "views": 12751,
        "channelName": "Zoom In Process",
        "channelId": "UCnIY-siVcBBMpVNJYgM3-OA",
        "channelAvatar": "https://yt3.googleusercontent.com/NK1Msx450Uy4LHnuEaMoHmyDghHcjNkK1X4C1_b_nvt3niMCsePiptTi8pNCMqwN2T0OLfAU=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=fq-QAU_7Uek"
    },
    {
        "title": "10/12(월) 🔥김홍택프로와 한판대결🔥🎁이벤트도 진행중입니다🎁[볼빅어패럴 프로VS아마 라이브]",
        "videoId": "uFNIK_XasbU",
        "thumbnail": "https://i.ytimg.com/vi/uFNIK_XasbU/maxresdefault.jpg",
        "published": "2026-10-02T04:00:21+00:00",
        "views": 506,
        "channelName": "GOLFZON",
        "channelId": "UClgieCzaMtSRPBJiUfgcXzg",
        "channelAvatar": "https://yt3.googleusercontent.com/Nt8dmJ7Ivo_ainOhzHz0ZHrnIZD8ypYa546m15C19Cv9iNN4W3-N87c1oF2Et8EBRM8mFawR=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=uFNIK_XasbU"
    },
    {
        "title": "쉽지않은 국가대표 선수의 튀르키예 리그 도전기 - 튀르키예(下)",
        "videoId": "mPfWTTs4O6s",
        "thumbnail": "https://i.ytimg.com/vi/mPfWTTs4O6s/maxresdefault.jpg",
        "published": "2026-09-30T09:00:39+00:00",
        "views": 1308570,
        "channelName": "곽튜브",
        "channelId": "UClRNDVO8093rmRTtLe4GEPw",
        "channelAvatar": "https://yt3.googleusercontent.com/whpRwLKLoWAQCwYCbr9Hq4xXF67ktW18y86VDdiMK4xS2xy_rVRMwIO3pf93QI-eZ_sAs7j-jQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=mPfWTTs4O6s"
    },
    {
        "title": "신기하게 양덕들이 더 환장한다 [도쿄게임쇼 탐방기: 나혼자만 레벨업 카르마]",
        "videoId": "SFWdIVCAqYY",
        "thumbnail": "https://i.ytimg.com/vi/SFWdIVCAqYY/maxresdefault.jpg",
        "published": "2026-09-30T10:34:17+00:00",
        "views": 158502,
        "channelName": "김성회의 G식백과",
        "channelId": "UCZ0bi2aVJngKLwFTU5g_fLQ",
        "channelAvatar": "https://yt3.googleusercontent.com/QdNUmlHPUq8iyHgU-7TZWnNjAXOa3vmb-fWVStmBJdUXmoPzCNr-0iaHkfeBgglYnYnVfBE_kA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=SFWdIVCAqYY"
    },
    {
        "title": "와... 여기 한국 맞나요?! ㄷㄷ",
        "videoId": "ajs5xOX6IOw",
        "thumbnail": "https://i.ytimg.com/vi/ajs5xOX6IOw/maxresdefault.jpg",
        "published": "2026-09-30T02:30:35+00:00",
        "views": 248000,
        "channelName": "Zools Kim",
        "channelId": "UCPTM-NMXolwmnUE_rjFIoYQ",
        "channelAvatar": "https://yt3.googleusercontent.com/zd3FeArIYKFI6TriTWZKW-gnfuzO7WVwrBuvNeifp2J-vP-3JeQHu3pZg8FqXMTs5qI4rExl=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=ajs5xOX6IOw"
    },
    {
        "title": "카이스트 테크토닉 전공 #김지석 #이장원",
        "videoId": "uXSaf7grR98",
        "thumbnail": "https://i.ytimg.com/vi/uXSaf7grR98/maxresdefault.jpg",
        "published": "2026-09-27T01:00:18+00:00",
        "views": 16939,
        "channelName": "김지석 [내 안의 보석]",
        "channelId": "UCrfMG9iLdCu1M6QpV8EZrTg",
        "channelAvatar": "https://yt3.googleusercontent.com/v6JV2AtnBm7ZLUJywX0E0MSl77P1JC2wq1PJosCHP6YH6F8hbEo90v2hMKsJR7vvpUmL9dMOUg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=uXSaf7grR98"
    },
    {
        "title": "초밥 800원, 오션뷰 호텔 2만원대ㄷㄷ 후쿠오카 갈 바엔 무조건 ‘여기’ 갑니다",
        "videoId": "i_YchbGodcc",
        "thumbnail": "https://i.ytimg.com/vi/i_YchbGodcc/maxresdefault.jpg",
        "published": "2026-09-30T09:00:24+00:00",
        "views": 1654429,
        "channelName": "꾸준 kkujun",
        "channelId": "UCxgeEPgtd5Aw7HgoEUXCauA",
        "channelAvatar": "https://yt3.googleusercontent.com/N549UWZcGKN0WFRf-FxT-QI2-4hSN68snN8ZHGxjF5q3GGDnWkTVckQbIGP5_RMi9vdcm7n_PA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=i_YchbGodcc"
    },
    {
        "title": "🔥【자바 기본편】출간 소식을 전해드립니다",
        "videoId": "LQPxcmW_XP4",
        "thumbnail": "https://i.ytimg.com/vi/LQPxcmW_XP4/maxresdefault.jpg",
        "published": "2026-04-24T11:00:43+00:00",
        "views": 2444,
        "channelName": "나도코딩",
        "channelId": "UC7iAOLiALt2rtMVAWWl4pnw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lU1PgVE4dvFxCmvzz72g_2-tzXfLfP1Dv16RAkPEvkIfc=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=LQPxcmW_XP4"
    },
    {
        "title": "1,000년 만에 모습을 드러낸 고대 마야의 거대한 손",
        "videoId": "Bdpa4pAt5cA",
        "thumbnail": "https://i.ytimg.com/vi/Bdpa4pAt5cA/maxresdefault.jpg",
        "published": "2026-09-28T09:00:04+00:00",
        "views": 33798,
        "channelName": "내셔널지오그래픽 - National Geographic Korea",
        "channelId": "UCPECLB_-7T4WukChKqhjv8g",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_ll9GD475ws_XC0CQQhVOB-F-_O9_1gO-hfQq1dZp2EgZU=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=Bdpa4pAt5cA"
    },
    {
        "title": "[MV] 달빛정원 - 메리크리스마스 투유 | Moonlight Garden - Merry Christmas to you",
        "videoId": "rWXAAc64abg",
        "thumbnail": "https://i.ytimg.com/vi/rWXAAc64abg/maxresdefault.jpg",
        "published": "2022-12-21T16:17:08+00:00",
        "views": 517,
        "channelName": "달빛정원 official",
        "channelId": "UCOj23ekvXa2S93YqX-AFSpw",
        "channelAvatar": "https://yt3.googleusercontent.com/0iiNIayRA48hyIesQtOxZmufXBCME8S9Wd-eCfEBM0GDasASBkDvESbbzdQAp4aa682MxFNjEQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=rWXAAc64abg"
    },
    {
        "title": "한양공주 고윤정 & 북부대공 허남준",
        "videoId": "9WTmRv0HVyE",
        "thumbnail": "https://i.ytimg.com/vi/9WTmRv0HVyE/maxresdefault.jpg",
        "published": "2026-09-23T02:00:00+00:00",
        "views": 1080637,
        "channelName": "돌고래유괴단",
        "channelId": "UCUsLcIQq0poAfOxRyJbxlLA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kKcQNBI0mxHn_GB6dXdNHVfdyPisVNCInGPGdPZU2iSkg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=9WTmRv0HVyE"
    },
    {
        "title": "16년 차 디자이너가 굳이 3D 프린터를 산 이유🖨️",
        "videoId": "Fm9siFWzQzc",
        "thumbnail": "https://i.ytimg.com/vi/Fm9siFWzQzc/maxresdefault.jpg",
        "published": "2026-09-29T09:17:15+00:00",
        "views": 5601,
        "channelName": "DGODWONCHAN design",
        "channelId": "UCvcGy6uMg0kwTyEab6hkSlQ",
        "channelAvatar": "https://yt3.googleusercontent.com/AT3EjyQ4EiN2YplbxwqrDjJlNP2bLlxezsVM20hSRT6L0rUTMAeqWDJhSvobSvXs-FGoJ4azpj4=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=Fm9siFWzQzc"
    },
    {
        "title": "이런 게 진짜 '증여'입니다.",
        "videoId": "RtO01hPdc4M",
        "thumbnail": "https://i.ytimg.com/vi/RtO01hPdc4M/maxresdefault.jpg",
        "published": "2026-09-30T23:00:04+00:00",
        "views": 19696,
        "channelName": "라이프코드 LIFECODE",
        "channelId": "UCaSHsWmh1CK8ptMAqSzDFCA",
        "channelAvatar": "https://yt3.googleusercontent.com/DZi9qY73thWGGVMo7m1JjDlLg3L5Sef26VfboOFzJFdxvbXASDG2wBIjlwWSyKSOeaun14eRkg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=RtO01hPdc4M"
    },
    {
        "title": "왕초보 클로드+힉스필드 MCP 사용법",
        "videoId": "qXcakvtE7nA",
        "thumbnail": "https://i.ytimg.com/vi/qXcakvtE7nA/maxresdefault.jpg",
        "published": "2026-09-11T02:19:02+00:00",
        "views": 592,
        "channelName": "띵킹프로그",
        "channelId": "UCUPYnmW2LuM0C1YlmYLW1vQ",
        "channelAvatar": "https://yt3.googleusercontent.com/VegCl61FaIqHdrnkJdQ1tGxRsfMDRM--glH7oImCy69ys1-GCrMrrs9Jc4qpacT05EF11doAtQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=qXcakvtE7nA"
    },
    {
        "title": "3D AI 툴, 게임 현업에 쓸 수 있을까? Tripo와 Meshy 살펴보기 - retr0 기술 노트",
        "videoId": "GSTtIwNoVs8",
        "thumbnail": "https://i.ytimg.com/vi/GSTtIwNoVs8/maxresdefault.jpg",
        "published": "2026-04-11T15:58:01+00:00",
        "views": 4860,
        "channelName": "레트로 retr0",
        "channelId": "UCRWq4MPqifkmT2GyL2d2ZAQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_ma57HnVh5OAQb2TsOCOHTPh-Stes5nV8XQ7UDJZa8Yhr4=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=GSTtIwNoVs8"
    },
    {
        "title": "제2회 벌스워크 X 노페어 게임대회 시상식",
        "videoId": "17k-AWc2o2o",
        "thumbnail": "https://i.ytimg.com/vi/17k-AWc2o2o/maxresdefault.jpg",
        "published": "2026-08-29T17:44:30+00:00",
        "views": 1282,
        "channelName": "노페어",
        "channelId": "UCMIyfh-0MQ9qcxF2Fiee8lA",
        "channelAvatar": "https://yt3.googleusercontent.com/QF08J51t8eSa2dBHhEz7-tfBtT5MNIH6q0YWCa4lPax3BiYKQoaV0Q7zOVQQCGrpwmX5wTWd=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=17k-AWc2o2o"
    },
    {
        "title": "AI 3D가 .. 한 단계 더 진화했습니다 I  최종보스 후보등장 I HI3D",
        "videoId": "MaXV3qAMAC8",
        "thumbnail": "https://i.ytimg.com/vi/MaXV3qAMAC8/maxresdefault.jpg",
        "published": "2026-06-12T06:13:45+00:00",
        "views": 1225740,
        "channelName": "LIM_blender",
        "channelId": "UC75_2AqLzrOAYWsEoUHHqyw",
        "channelAvatar": "https://yt3.googleusercontent.com/1cxF4I_CWl-0C1mgdF5YYwsnom3d4XzUbbhyunJ7sCwNtxkA00zovhzT22IuP-nlcuFRWfjFgg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=MaXV3qAMAC8"
    },
    {
        "title": "언제나 짜릿한 \"빼박 핵 증거\" 발견의 순간 [로사관 EP.14]",
        "videoId": "ClkOgcA8Jq8",
        "thumbnail": "https://i.ytimg.com/vi/ClkOgcA8Jq8/maxresdefault.jpg",
        "published": "2026-10-01T02:30:29+00:00",
        "views": 113735,
        "channelName": "로자르",
        "channelId": "UCuwnt_REmD4YsCtFJRoqjFw",
        "channelAvatar": "https://yt3.googleusercontent.com/X0fnkHuAHTMCek_H3Vlykz5Flm03aCny6LgAl7vm-La5nB-s9Vf7QfrrKabuIoa3g8Np_yPTDw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=ClkOgcA8Jq8"
    },
    {
        "title": "직접 만든 르세라핌 응원봉으로 촛불끄기. le sserafim lightstick swing",
        "videoId": "SSAlJ32iAJI",
        "thumbnail": "https://i.ytimg.com/vi/SSAlJ32iAJI/maxresdefault.jpg",
        "published": "2023-03-27T08:33:18+00:00",
        "views": 468,
        "channelName": "만드는사람 [MANDLER]",
        "channelId": "UCiYtB2kLBTcnvODuzAB0_WQ",
        "channelAvatar": "https://yt3.googleusercontent.com/NfKMw8f1OybSmqPvQiaq07bxIU3kvU4edGPwCUwnpq0nkc9ifoYrvQn8dLm1fvOvGpuPIIaW=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=SSAlJ32iAJI"
    },
    {
        "title": "예술의 세계로 초대하는 법(뻔하지 않게)",
        "videoId": "LlOqkdZwK8M",
        "thumbnail": "https://i.ytimg.com/vi/LlOqkdZwK8M/maxresdefault.jpg",
        "published": "2026-08-10T12:00:07+00:00",
        "views": 93,
        "channelName": "말하는 작업실 talking atelier",
        "channelId": "UCCEuLohDp1hc6zBmoUtpX3A",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_npJn8rauNz59cpsy9N5zW8TaSX6x5yvMkIWusWykZeCAA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=LlOqkdZwK8M"
    },
    {
        "title": "300% 마진남는 중국제품 내 브랜드로 팔아 200억 번 미친 방법 (수익인증)",
        "videoId": "_O2ItqANaro",
        "thumbnail": "https://i.ytimg.com/vi/_O2ItqANaro/maxresdefault.jpg",
        "published": "2026-09-30T13:15:22+00:00",
        "views": 9190,
        "channelName": "머니로드 - 돈 길치 가이드",
        "channelId": "UCucFucgJnJKJRTEaO-_Fqsw",
        "channelAvatar": "https://yt3.googleusercontent.com/hHTPVxaR8iOYL17Y-G-Xn3pSj572ymTFuLWsfTALzPim0pZLUw9ZY-6sAyl4kO5JdpbWX2c0nmE=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=_O2ItqANaro"
    },
    {
        "title": "서울메이커페어 2026 스케치 영상 #3d프린터 #이제는일상",
        "videoId": "EVcg3UHeJOo",
        "thumbnail": "https://i.ytimg.com/vi/EVcg3UHeJOo/maxresdefault.jpg",
        "published": "2026-09-19T14:54:06+00:00",
        "views": 652,
        "channelName": "메이커 다은쌤",
        "channelId": "UC-TbOuCyTywTg9G9e_LWAbg",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_nYifclJYD0CVCJTcYp8HCTbehDbuNxNDVXbt-RgNfbkdE=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=EVcg3UHeJOo"
    },
    {
        "title": "PG Nu Gundam Unleashed - #103. 스커트 프레임 모델링(10)",
        "videoId": "C4jazHZ_k5A",
        "thumbnail": "https://i.ytimg.com/vi/C4jazHZ_k5A/maxresdefault.jpg",
        "published": "2026-02-13T14:04:17+00:00",
        "views": 556,
        "channelName": "바라기_Fusion Solution",
        "channelId": "UCRvocyhMAyvU_f_fMDE9abA",
        "channelAvatar": "https://yt3.googleusercontent.com/yyfe3CWj8HtVqN4_GQy8HETgH6HD60x43zGqpSBuKtQRziklAyl7Fwq0r-WBojOMUZexPRM6MHc=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=C4jazHZ_k5A"
    },
    {
        "title": "홍점알락나비",
        "videoId": "MepXyYrLJZU",
        "thumbnail": "https://i.ytimg.com/vi/MepXyYrLJZU/maxresdefault.jpg",
        "published": "2026-08-01T09:07:30+00:00",
        "views": 90,
        "channelName": "벌레랑헤벌레_bugNjoy",
        "channelId": "UCyU8tEnxyrGTPgPXQ47bGog",
        "channelAvatar": "https://yt3.googleusercontent.com/dTls1LgogZlSJXJ6_li2qXWfQgSPM5OpuBKTGRoxO6_r65g1f7uwzImhF9TFqDfcJLZPwDiE0g=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=MepXyYrLJZU"
    },
    {
        "title": "Claude Opus 5.5 프롬프트 한 줄로 만든 영상 (프롬프트 공유)",
        "videoId": "A8jC71NQoqM",
        "thumbnail": "https://i.ytimg.com/vi/A8jC71NQoqM/maxresdefault.jpg",
        "published": "2026-09-30T01:25:19+00:00",
        "views": 1760,
        "channelName": "빵형의 개발도상국",
        "channelId": "UC9PB9nKYqKEx_N3KM-JVTpg",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_nXbFN_SjZuCqP9isEDXrWRTWq9uAlmvbj5rb24sV3Wtg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=A8jC71NQoqM"
    },
    {
        "title": "300만 년 된 뇌가 스마트폰을 만났을 때 일어나는 일 [북툰 과학다큐]",
        "videoId": "ZPjy3bcCYD8",
        "thumbnail": "https://i.ytimg.com/vi/ZPjy3bcCYD8/maxresdefault.jpg",
        "published": "2026-09-01T09:56:42+00:00",
        "views": 128584,
        "channelName": "북툰",
        "channelId": "UCpZUM8lQBdgzo3avQqtmQvw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lyku2muAltQHseRbZtXobj1fOv2c8TxRbXRFtjn4xF6UI=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=ZPjy3bcCYD8"
    },
    {
        "title": "스풀터진 뱀부랩 필라멘트 복구 Live",
        "videoId": "M9P3sepTYZ8",
        "thumbnail": "https://i.ytimg.com/vi/M9P3sepTYZ8/maxresdefault.jpg",
        "published": "2026-09-23T12:55:02+00:00",
        "views": 4079,
        "channelName": "북리지",
        "channelId": "UCl3N7XHLxcAeVtTZajvPatw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_me9AuK4lr9Vz_QzW-JR6Lpio18SGE1H53CdnOLxYoxq6k=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=M9P3sepTYZ8"
    },
    {
        "title": "칫솔 만들기",
        "videoId": "S8LdzkGRwx8",
        "thumbnail": "https://i.ytimg.com/vi/S8LdzkGRwx8/maxresdefault.jpg",
        "published": "2026-10-01T09:00:12+00:00",
        "views": 398625,
        "channelName": "3D SANAGO",
        "channelId": "UCd4FmcWIVdWAy0-Q8OJBloQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_nN-7Vdy0T2PEWo5palhhFWXuNaDYqGDlLYX_FR-96qbmQa=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=S8LdzkGRwx8"
    },
    {
        "title": "AI로 쓴 글, 다 비슷합니다",
        "videoId": "NrS5L1BNClg",
        "thumbnail": "https://i.ytimg.com/vi/NrS5L1BNClg/maxresdefault.jpg",
        "published": "2026-09-27T10:28:04+00:00",
        "views": 825,
        "channelName": "Science Adam",
        "channelId": "UC3ofpYNO2gLwV0fgcuFG8tA",
        "channelAvatar": "https://yt3.googleusercontent.com/RMr0leul1UR6vcO1bfiwPbOP9IGS2GZdZOT4g0OWzf5ORfu3IQy-wz7YuS8df7zTKUPAp4Fk=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=NrS5L1BNClg"
    },
    {
        "title": "⏱️2시 마켓워치 시작합니다!⏱️ㅣ권다영, 이지환, 김태성 [2시 마켓워치]",
        "videoId": "Ima4xO_MR0w",
        "thumbnail": "https://i.ytimg.com/vi/Ima4xO_MR0w/maxresdefault.jpg",
        "published": "2026-10-02T04:01:09+00:00",
        "views": 14498,
        "channelName": "삼프로TV 3PROTV",
        "channelId": "UChlv4GSd7OQl3js-jkLOnFA",
        "channelAvatar": "https://yt3.googleusercontent.com/--qajlNgqpwDCjcupwfYwXsgXS3szfhMEEFGI1ouLTj4CKOtwGOyXGR7xl8-tzOGCDFt9umfqQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=Ima4xO_MR0w"
    },
    {
        "title": "DNA를 복구하면 노화를 막을 수 있을까? | 미국 현지 촬영 | 하버드 하택집 교수 | 샤로잡다 시즌2 (ENG CC)",
        "videoId": "iIsUV1GSJk8",
        "thumbnail": "https://i.ytimg.com/vi/iIsUV1GSJk8/maxresdefault.jpg",
        "published": "2026-10-01T08:00:37+00:00",
        "views": 14080,
        "channelName": "서울대학교 Seoul National University",
        "channelId": "UCJ_3L5ElVq7fI0AAB91tfng",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lltiYANJ3VigbFtY0UrnB7Jps3C-HqKBD_smuZ6cRzhg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=iIsUV1GSJk8"
    },
    {
        "title": "해보지도 않고 포기하는 사람들의 공통점",
        "videoId": "m9_fM6rsyIg",
        "thumbnail": "https://i.ytimg.com/vi/m9_fM6rsyIg/maxresdefault.jpg",
        "published": "2026-10-02T03:20:40+00:00",
        "views": 863,
        "channelName": "세바시 강연 Sebasi Talk",
        "channelId": "UCgheNMc3gGHLsT-RISdCzDQ",
        "channelAvatar": "https://yt3.googleusercontent.com/r7kVqIDUDyGQvmbOdi1GNAahUHaHPZl8Z92gSfSlWSdQOEr2kFgSsQQhAzUHvRxfYdTAasLatA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=m9_fM6rsyIg"
    },
    {
        "title": "로직의 이펙터는 정말로 좋다 #음악프로듀싱",
        "videoId": "xSP4aX_K7uo",
        "thumbnail": "https://i.ytimg.com/vi/xSP4aX_K7uo/maxresdefault.jpg",
        "published": "2026-10-01T09:31:46+00:00",
        "views": 882,
        "channelName": "songcamp99",
        "channelId": "UCyQIQANQ0qToMUxFJ9C494g",
        "channelAvatar": "https://yt3.googleusercontent.com/87ALPvgKnnMAwl2PLaamGcX7UUe2L7ZY1WdLRAVCTBJGPM-D4dLiLf2EKUf6cma6PSliA7cC=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=xSP4aX_K7uo"
    },
    {
        "title": "신종 투자리딩방 사기가 판을 치고 있습니다. 천하의 나쁜 놈들!",
        "videoId": "vbDEHKhogXU",
        "thumbnail": "https://i.ytimg.com/vi/vbDEHKhogXU/maxresdefault.jpg",
        "published": "2026-10-01T09:44:51+00:00",
        "views": 642794,
        "channelName": "슈카월드",
        "channelId": "UCsJ6RuBiTVWRX156FVbeaGg",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kqf6MgVU6c8LWzVAVqpggLLS4bTxdKe_aiQzM17HsqRhk=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=vbDEHKhogXU"
    },
    {
        "title": "Respect",
        "videoId": "hNco4CbATVE",
        "thumbnail": "https://i.ytimg.com/vi/hNco4CbATVE/maxresdefault.jpg",
        "published": "2025-11-07T09:31:28+00:00",
        "views": 2925011,
        "channelName": "스토리",
        "channelId": "UCm2PiWccs-otbzhjiNXHu5g",
        "channelAvatar": "https://yt3.googleusercontent.com/ArBE4TRbn2hcjtgT8OCJpEPFG6mMOb7dI_SlP7UYBfjol6LdM3o3_nx2tB6DtiviRTgrQBL9FQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=hNco4CbATVE"
    },
    {
        "title": "AI 경쟁은 이제... 새로운 플랫폼 경쟁으로... 애플, 구글에서 벗어난 메타의 안경부터 OpenAI의 작업 공간까지… AI 기업들이 일상을 파고드는 이유",
        "videoId": "w7b_oqMVJEg",
        "thumbnail": "https://i.ytimg.com/vi/w7b_oqMVJEg/maxresdefault.jpg",
        "published": "2026-10-01T08:18:30+00:00",
        "views": 61397,
        "channelName": "안될공학 - IT 테크 신기술",
        "channelId": "UCeN2YeJcBCRJoXgzF_OU3qw",
        "channelAvatar": "https://yt3.googleusercontent.com/hStraaByOVLDs0eye3XmjD7l1pkYEb9DwGwRhOM5RdOfG-thmMTt0ozg3EOTDcxM-D-S2BlcyA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=w7b_oqMVJEg"
    },
    {
        "title": "아무나 배우는 C++ 프로그래밍 - 배열, 포인터, 참조",
        "videoId": "69syQKW6Skw",
        "thumbnail": "https://i.ytimg.com/vi/69syQKW6Skw/maxresdefault.jpg",
        "published": "2022-06-19T11:48:49+00:00",
        "views": 11850,
        "channelName": "안리얼",
        "channelId": "UCtBHTULQbAEg5QbkcZc_Tdw",
        "channelAvatar": "https://yt3.googleusercontent.com/Bcnk8heNmhwt94CM_l2GSPb8pZI946PYMQ38QDDJ3Ac09FDvLrTioa4HeP0qC5SIOwBkaLveXtw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=69syQKW6Skw"
    },
    {
        "title": "전 연인의 흔적",
        "videoId": "T6qOEc8psig",
        "thumbnail": "https://i.ytimg.com/vi/T6qOEc8psig/maxresdefault.jpg",
        "published": "2024-10-05T05:00:30+00:00",
        "views": 68320,
        "channelName": "스튜디오 와플 - STUDIO WAFFLE",
        "channelId": "UCYtjW8dGkaeHwrMiB01Xa_Q",
        "channelAvatar": "https://yt3.googleusercontent.com/L2Ox6kbIxcnujmxVbtPSOGvRcpSNOIBbTKEKw1EvpD_LWsAcLTwryTrtUZiHwKVgV0AGbbIfAk8=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=T6qOEc8psig"
    },
    {
        "title": "원래 단편으로 제작됐다가 \"넷플릭스 1위\" 찍고, 곧바로 시즌2 제작해버린 역대급 스릴러【시즌1 몰아보기】",
        "videoId": "a_3SZW1pVRc",
        "thumbnail": "https://i.ytimg.com/vi/a_3SZW1pVRc/maxresdefault.jpg",
        "published": "2026-08-09T10:30:20+00:00",
        "views": 189103,
        "channelName": "양쟈까의 La View",
        "channelId": "UCrsYoNklsxEQSGQEduLsIFg",
        "channelAvatar": "https://yt3.googleusercontent.com/LKmVdjc3cvjx8cqCpt_CvJyDluSr5cE80_PxgImwQI-EnON9l2maAF8sDCF1UUj4bSSCCc_daA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=a_3SZW1pVRc"
    },
    {
        "title": "언리얼로 만드는 소울라이크 게임 포트폴리오! Karma Unbound",
        "videoId": "-X2uEDaR7UQ",
        "thumbnail": "https://i.ytimg.com/vi/-X2uEDaR7UQ/maxresdefault.jpg",
        "published": "2026-09-30T09:00:31+00:00",
        "views": 618,
        "channelName": "어소트락 게임아카데미",
        "channelId": "UCOPlo0wPx7Uo4p8e3GaW2KQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lMx6T4l-WEG0zP_WrjYdF5JaYBHed63b6Prqdu-fLeUg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=-X2uEDaR7UQ"
    },
    {
        "title": "OC Clip Studio Timelapes #shorts  #oc",
        "videoId": "kLepp6ujiK8",
        "thumbnail": "https://i.ytimg.com/vi/kLepp6ujiK8/maxresdefault.jpg",
        "published": "2024-08-01T08:41:52+00:00",
        "views": 111,
        "channelName": "어떤 주머니쥐의 타임캡슐",
        "channelId": "UC1LgvGArlf2XvWGCaEBFjJQ",
        "channelAvatar": "https://yt3.googleusercontent.com/2QtNlRw6ipAQcj5WYLtWDuvLZY8FQDWhXAQ_JLeRGstJ4aGHyNz65peniRa_yR9SLmsuibRfXA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=kLepp6ujiK8"
    },
    {
        "title": "LG 엑사원 실사용 후기",
        "videoId": "Liexsr1QAHM",
        "thumbnail": "https://i.ytimg.com/vi/Liexsr1QAHM/maxresdefault.jpg",
        "published": "2026-10-01T11:00:05+00:00",
        "views": 5118,
        "channelName": "Softdragon SOD",
        "channelId": "UCSPMRoAphbObUYeDaX367Fg",
        "channelAvatar": "https://yt3.googleusercontent.com/2blVx3rsIkp_x1FNrVmdctIHyZgVAkP7MjiEr4iFqYmbyUDw0pL7IsXq6-XbBVmrzmo7eC5QPg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=Liexsr1QAHM"
    },
    {
        "title": "빅테크가 뛰어든 시장에서 작은 팀이 살아남는 방법 | 티로 CTO 김상철",
        "videoId": "3oTRcw6DDBI",
        "thumbnail": "https://i.ytimg.com/vi/3oTRcw6DDBI/maxresdefault.jpg",
        "published": "2026-09-11T09:53:27+00:00",
        "views": 1301,
        "channelName": "엔드플랜 Endplan AI",
        "channelId": "UCZ4mb62ECiTMw8DcbBcMLmA",
        "channelAvatar": "https://yt3.googleusercontent.com/BuE-16-AhNnWcjdg0Zlsd3i7z0voSM9J9uN-zjkxc5JFZU72jarYI2d6so1QmfdB_sYIvtOvGQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=3oTRcw6DDBI"
    },
    {
        "title": "완성도 미쳤다! 실제 운영 가능 AI 홈페이지 만들기 | 뉴스레터, 로그인·구독·AI 챗봇을 한 번에 (Manus) | 오후다섯씨",
        "videoId": "RWOpR9mjXd8",
        "thumbnail": "https://i.ytimg.com/vi/RWOpR9mjXd8/maxresdefault.jpg",
        "published": "2026-09-27T10:25:50+00:00",
        "views": 7087,
        "channelName": "Mr.5pm",
        "channelId": "UCgMUR5LrlKuP6Ot0ZBem8Nw",
        "channelAvatar": "https://yt3.googleusercontent.com/tCbd2AERfr4DjkC01rR2ngvIPHrvD_LX96hRx5EwBdVS-Ek81_QtjGpBEzq3ZVLKmOCt39WafmY=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=RWOpR9mjXd8"
    },
    {
        "title": "갤럭시 백업 설정 당장 확인하세요; 10월부터 전부 안 보입니다 #shorts",
        "videoId": "9qpytLZbLDg",
        "thumbnail": "https://i.ytimg.com/vi/9qpytLZbLDg/maxresdefault.jpg",
        "published": "2026-09-29T23:00:10+00:00",
        "views": 3546,
        "channelName": "오목교 전자상가",
        "channelId": "UCCQPdv4o4ywVZQkAMOlvFbw",
        "channelAvatar": "https://yt3.googleusercontent.com/ffyVds9XBZ4jZZ-V0JHQxdFSXeaJEiwMWI08udXosApDYAYwmXWiRQaEFDNQLN_r7d57rNp77xY=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=9qpytLZbLDg"
    },
    {
        "title": "Oil pastel drawing / Winter drawing / 오일파스텔로 눈 내린 풍경 그리기",
        "videoId": "q4z_n857gGU",
        "thumbnail": "https://i.ytimg.com/vi/q4z_n857gGU/maxresdefault.jpg",
        "published": "2023-12-23T10:16:57+00:00",
        "views": 10236,
        "channelName": "오후의 시아 Ohu Sia",
        "channelId": "UCh5to1SgKQt9tkHaPYyt3Mw",
        "channelAvatar": "https://yt3.googleusercontent.com/hWc4BF625qaA5gT9kTwbEh_DI1EJbWNVQJqHmZ61mGvYM6x1YWupkJN0SZ2MDAsoSQ5AAhn9=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=q4z_n857gGU"
    },
    {
        "title": "제작비 5천만원짜리 퀄리티 광고, 50만원에 나왔습니다.",
        "videoId": "IB5Q_BfGc2I",
        "thumbnail": "https://i.ytimg.com/vi/IB5Q_BfGc2I/maxresdefault.jpg",
        "published": "2026-09-21T09:15:03+00:00",
        "views": 16446,
        "channelName": "WENSON",
        "channelId": "UC4AVc-iIPWIDl6TTi92TS2Q",
        "channelAvatar": "https://yt3.googleusercontent.com/WI0xvhV9QA_eIPCH5WllsXf9JcF2u-bzjHRVOyax9MYHXIYMX849VKBLdh0So6fx8tNlC1i0=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=IB5Q_BfGc2I"
    },
    {
        "title": "[#세상에이런일이] 희귀질환을 낫게 해준 재희와 뗄 수 없는 존재🛹#우와비",
        "videoId": "fc_NxaB7zEw",
        "thumbnail": "https://i.ytimg.com/vi/fc_NxaB7zEw/maxresdefault.jpg",
        "published": "2026-10-01T08:00:26+00:00",
        "views": 5341,
        "channelName": "우와한 비디오",
        "channelId": "UC0PsUG07plnP_uQQS9djFVQ",
        "channelAvatar": "https://yt3.googleusercontent.com/QUPWozpOgvTiCbh31iXRf5ETm15s-0jLuEZR_vV8DHaJe_jdHctkRWN7iq6BxAqPeS8tr53Y=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=fc_NxaB7zEw"
    },
    {
        "title": "실사 같은 타일 만드는 법 [Enscape & V-Ray]",
        "videoId": "ACo4_uelC5k",
        "thumbnail": "https://i.ytimg.com/vi/ACo4_uelC5k/maxresdefault.jpg",
        "published": "2026-09-21T11:45:26+00:00",
        "views": 2607,
        "channelName": "용센의 스케치업",
        "channelId": "UCm99gAFMgfpLioR5-_G5wjw",
        "channelAvatar": "https://yt3.googleusercontent.com/MxhreaNll132VjJyujc7JwT_fwaVPGUzbqIhT7zCkuqvsvF068r2QE3V8Nu8Jn_qp1meEqRj=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=ACo4_uelC5k"
    },
    {
        "title": "AI 모션 캡쳐 + 블렌더 + Seedance 2.0로 댄스 커버 + 립싱크 영상 만들기",
        "videoId": "vdEBDrE55cc",
        "thumbnail": "https://i.ytimg.com/vi/vdEBDrE55cc/maxresdefault.jpg",
        "published": "2026-07-21T01:53:38+00:00",
        "views": 19075,
        "channelName": "이르키 | iRKi",
        "channelId": "UCdP0FJ2Z8dbl1fu6NjDJryA",
        "channelAvatar": "https://yt3.googleusercontent.com/Fc34t-4Sds0dj4T1jdvwIDMNlaMfCnAp2GNGuAxY7waJatjTcXQZdCFdi_tBUp1Zz4VZWx773i0=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=vdEBDrE55cc"
    },
    {
        "title": "청량리역 대합실 비둘기",
        "videoId": "0C-8GdFjyFo",
        "thumbnail": "https://i.ytimg.com/vi/0C-8GdFjyFo/maxresdefault.jpg",
        "published": "2026-04-13T09:37:10+00:00",
        "views": 369,
        "channelName": "이승규 (Sunbird)",
        "channelId": "UCgmX1Pxf8-Igul5L0Ie5DqA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_k3HyK8qUdmhyy7K5YFBVe5-Y831bO3_0r3orPXEoKaSQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=0C-8GdFjyFo"
    },
    {
        "title": "Youtube 치지직 API 연동 테스트",
        "videoId": "QBpxmwvxfUs",
        "thumbnail": "https://i.ytimg.com/vi/QBpxmwvxfUs/maxresdefault.jpg",
        "published": "2025-10-11T18:30:19+00:00",
        "views": 437,
        "channelName": "윤농 Yunnong",
        "channelId": "UCFzoKNDfvq7YyyAGqp9iHZA",
        "channelAvatar": "https://yt3.googleusercontent.com/Y6mlBVc5G1KVLQNfufAleGyLPfgA_ExQxXbROWdH2M788sdOhS2OPy7XvRVUvAsxs72GK5tumQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=QBpxmwvxfUs"
    },
    {
        "title": "군상아, 무슨 일이야?",
        "videoId": "sdqj5re5fyU",
        "thumbnail": "https://i.ytimg.com/vi/sdqj5re5fyU/maxresdefault.jpg",
        "published": "2026-09-08T01:15:44+00:00",
        "views": 109,
        "channelName": "이응노미술관(LEE UNGNO MUSEUM)",
        "channelId": "UC5WunGpOXmdUGlNw4gtouBA",
        "channelAvatar": "https://yt3.googleusercontent.com/3-07Znsy4AXdp6bBaTKrajV9DczmF5zUdD8wHPDu9nc_EwNAo29UFwFAC1bOdwQnTv-PhDSEzeo=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=sdqj5re5fyU"
    },
    {
        "title": "[혼자하는 오사카 여행] - 아이폰 8+,스무스4 촬영",
        "videoId": "xbeQdIErs0A",
        "thumbnail": "https://i.ytimg.com/vi/xbeQdIErs0A/maxresdefault.jpg",
        "published": "2018-09-27T15:18:21+00:00",
        "views": 8596,
        "channelName": "이쿠마",
        "channelId": "UCHlqnw3Oy_Z8iQWNaiEdNCQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lsZzy9cpK6F02Vq7UguKqHwwnofH_ISeY3W5YgYBvb4A=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=xbeQdIErs0A"
    },
    {
        "title": "THE GREAT MONGOLIA",
        "videoId": "l1APXVFC8zk",
        "thumbnail": "https://i.ytimg.com/vi/l1APXVFC8zk/maxresdefault.jpg",
        "published": "2026-09-15T14:05:48+00:00",
        "views": 1288,
        "channelName": "Freelancer Jin",
        "channelId": "UCklI1dk1q5GEb36D69LBGVg",
        "channelAvatar": "https://yt3.googleusercontent.com/JNEaLY8iCIz5lrL8IIPSztpeWgkkPjOdh8iBdJmQW1jscYJGH9IcHIiwFrFbAqeU95ix6y9cZXo=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=l1APXVFC8zk"
    },
    {
        "title": "월매출 150억 장사의신이 모델 절대 안쓰는 이유.",
        "videoId": "rVvf9277YjI",
        "thumbnail": "https://i.ytimg.com/vi/rVvf9277YjI/maxresdefault.jpg",
        "published": "2026-10-02T01:47:51+00:00",
        "views": 41034,
        "channelName": "장사의 신",
        "channelId": "UCBMBPRnwRgl3aJZDEpTu65Q",
        "channelAvatar": "https://yt3.googleusercontent.com/wu3oIut73_FSy0Qs4aNyywBlV2Lk5HqZS1e9XjUef9Dx_r9XC99b4ujeywXRiIwzKAXioun0eQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=rVvf9277YjI"
    },
    {
        "title": "승급의 악마",
        "videoId": "8rkrTohINSI",
        "thumbnail": "https://i.ytimg.com/vi/8rkrTohINSI/maxresdefault.jpg",
        "published": "2026-09-29T09:30:32+00:00",
        "views": 364685,
        "channelName": "정서불안 김햄찌",
        "channelId": "UCU5Bngb-griCg_96ZXpXOgg",
        "channelAvatar": "https://yt3.googleusercontent.com/DtnsCJ0mRt8kgaWDoQDhgLcEN6TM8e5a6g7HPrRsShn43grqd0HOoteYkZuyfge01fWtki5r=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=8rkrTohINSI"
    },
    {
        "title": "왜 나폴레옹은 최고의 시계를 갖고 싶어 했나? | 조승연 작가 꿈의시계 차봤습니다",
        "videoId": "D7AVY_VPoEY",
        "thumbnail": "https://i.ytimg.com/vi/D7AVY_VPoEY/maxresdefault.jpg",
        "published": "2026-09-19T01:20:35+00:00",
        "views": 298139,
        "channelName": "조승연의 탐구생활",
        "channelId": "UCvW8norVMTLt7QN-s2pS4Bw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lXoW3ALo9m0kgpIq60EDChhqBRx4OE-i7gBWKDKENKYg=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=D7AVY_VPoEY"
    },
    {
        "title": "와.. 도파민 대폭발 개미친 예능 떴다...",
        "videoId": "OZuya34ciyg",
        "thumbnail": "https://i.ytimg.com/vi/OZuya34ciyg/maxresdefault.jpg",
        "published": "2026-10-01T09:20:02+00:00",
        "views": 295499,
        "channelName": "지무비 : G Movie",
        "channelId": "UCaHGOzOyeYzLQeKsVkfLEGA",
        "channelAvatar": "https://yt3.googleusercontent.com/7Tnxb_PQu3oLQj1IYv3IJ3rv_S4YyyqY3fazd4yCg_kePd9DKalomOPIz6DBR-l_ItHyPHF6Pko=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=OZuya34ciyg"
    },
    {
        "title": "전공자가 알려주는 그림 연습 꿀팁",
        "videoId": "pXUKA3j2UQY",
        "thumbnail": "https://i.ytimg.com/vi/pXUKA3j2UQY/maxresdefault.jpg",
        "published": "2026-09-30T11:01:29+00:00",
        "views": 24256,
        "channelName": "쥬캔버스 JOOCANVAS",
        "channelId": "UCHBSeh2viERcTJFB3h27GVw",
        "channelAvatar": "https://yt3.googleusercontent.com/MEFJYKxklqGkEA4NACLbM9wuuk7k6qbaZmGjYx0snhrvesZQqSmKGzmJP_Z0cd3K_pckM1y3kQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=pXUKA3j2UQY"
    },
    {
        "title": "🚨 AI응답 자체가 사기일 수 있다?? 신종 사기 수법 등장 ㄷㄷ",
        "videoId": "SL5SJMe48qA",
        "thumbnail": "https://i.ytimg.com/vi/SL5SJMe48qA/maxresdefault.jpg",
        "published": "2026-10-02T06:00:37+00:00",
        "views": 160,
        "channelName": "조코딩 JoCoding",
        "channelId": "UCQNE2JmbasNYbjGAcuBiRRg",
        "channelAvatar": "https://yt3.googleusercontent.com/6gJoxwN9IQ3SlQIo1SibzhmwNLfxhX3t15zfQAGMxmV3Fi7aALzNayf2CzqhL5U6c2f4123G=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=SL5SJMe48qA"
    },
    {
        "title": "[함께 일해요] 웹툰 작가와 고양이가 일할 때 듣는 경쾌한 팝송 노동요 Playlist",
        "videoId": "83aR29VJ-_I",
        "thumbnail": "https://i.ytimg.com/vi/83aR29VJ-_I/maxresdefault.jpg",
        "published": "2021-03-02T05:00:34+00:00",
        "views": 9934,
        "channelName": "천계영의 창작생활",
        "channelId": "UC-FL_yFyVsmgYodyqOooamQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_lP2JdIiNUrVeA3zxMWvq_yiiNKTnMrhM2Ulk0G_rZ42g=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=83aR29VJ-_I"
    },
    {
        "title": "LA는 코끼리 코 안 해요? #나나기획",
        "videoId": "uHrpyWoixCQ",
        "thumbnail": "https://i.ytimg.com/vi/uHrpyWoixCQ/maxresdefault.jpg",
        "published": "2026-10-01T23:00:38+00:00",
        "views": 24012,
        "channelName": "channel fullmoon",
        "channelId": "UCQ2O-iftmnlfrBuNsUUTofQ",
        "channelAvatar": "https://yt3.googleusercontent.com/A-fAX_0w8QWox9AM2VjHz5he9_s7koCRyX_p8BEvMQPa4PFSDU84Y5YyByoRzeeJvxiZ9kuL94U=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=uHrpyWoixCQ"
    },
    {
        "title": "핸드폰 가게에 ‘공짜폰’은 진짜 공짜일까?",
        "videoId": "8TtP0OxxPr0",
        "thumbnail": "https://i.ytimg.com/vi/8TtP0OxxPr0/maxresdefault.jpg",
        "published": "2026-09-26T03:00:29+00:00",
        "views": 581868,
        "channelName": "JinYongJin",
        "channelId": "UCIG4gr_wIy5CIlcFciUbIQw",
        "channelAvatar": "https://yt3.googleusercontent.com/fMURYix9tjm6UON2-GoIRRG33S3AufQuo6fRmFtd1Q6xBnTghkiuDqeQskpNrHz-48vnhnOSfw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=8TtP0OxxPr0"
    },
    {
        "title": "상위 3% 엄마의 대화법, 가정에서 이렇게 가르치면 아이는 반드시 성장합니다 [최민준]",
        "videoId": "13HCUwKfi6A",
        "thumbnail": "https://i.ytimg.com/vi/13HCUwKfi6A/maxresdefault.jpg",
        "published": "2026-09-21T12:00:33+00:00",
        "views": 97691,
        "channelName": "최민준의 아들TV",
        "channelId": "UC5m1d4sPHnpcLCJEu3j2FpQ",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_mmCaYuLoTrlFE_dilc_nO82WFqF8mbngkjLIgHSIRwuQ=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=13HCUwKfi6A"
    },
    {
        "title": "법 보다 이슬람? 심상치 않은 프랑스 무슬림 근황 [지구본 뉴스룸]",
        "videoId": "69QvyMteB00",
        "thumbnail": "https://i.ytimg.com/vi/69QvyMteB00/maxresdefault.jpg",
        "published": "2026-09-30T09:00:01+00:00",
        "views": 395620,
        "channelName": "최준영 박사의 지구본 연구소",
        "channelId": "UCstI8HwGQsHdqLDgyH0PImw",
        "channelAvatar": "https://yt3.googleusercontent.com/RY3WPNbGI8J8GqTEmgXcHE2CkzR4we1ejWxQ1DNK0Qjiyt6nNslNJCd_YOkcW6AKaevuhYCuUw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=69QvyMteB00"
    },
    {
        "title": "맨땅에 게임 아트 그리기",
        "videoId": "OwBQZ6n_PYE",
        "thumbnail": "https://i.ytimg.com/vi/OwBQZ6n_PYE/maxresdefault.jpg",
        "published": "2026-09-18T12:47:16+00:00",
        "views": 12376,
        "channelName": "최라마",
        "channelId": "UCjlpFIYLw7mwO0ys5tu19hw",
        "channelAvatar": "https://yt3.googleusercontent.com/Id8XPKrtB8ursLPfezBtzHDDTV0rcP-bKDK4Wt_N1imz534Awcw7QkyHqOKjxZtb2GQPFdTyxPk=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=OwBQZ6n_PYE"
    },
    {
        "title": "행보관 보스전을 개발 중 #예비군시뮬레이터 #1인개발 #예비군 #게임 #군대",
        "videoId": "aqZwr9DL3fM",
        "thumbnail": "https://i.ytimg.com/vi/aqZwr9DL3fM/maxresdefault.jpg",
        "published": "2026-04-21T08:58:24+00:00",
        "views": 4781,
        "channelName": "Unreal as a hobby",
        "channelId": "UCpYNscud7EdXvJE2QAHrvsQ",
        "channelAvatar": "https://yt3.googleusercontent.com/QGs20Y1944NX9oWPVT2PVPnx5XWkpWiICIk9f5V8eEj80APVitGaaRq9WsEiHYwWEl11oBJA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=aqZwr9DL3fM"
    },
    {
        "title": "AI가 뽑은 🚀한국 축구 역대 베스트 일레븐",
        "videoId": "Qc5GhluWNPU",
        "thumbnail": "https://i.ytimg.com/vi/Qc5GhluWNPU/maxresdefault.jpg",
        "published": "2024-02-03T11:02:10+00:00",
        "views": 64909,
        "channelName": "코딩하는거니",
        "channelId": "UCO7g158NWgLyn98z8v3zduA",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kY8GGdOFxIAhZAzX80P5v0E8zCydKgECchBSaPJ2M0=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=Qc5GhluWNPU"
    },
    {
        "title": "SK 하이닉스를 갈 마지막 기회",
        "videoId": "w0rf4kB3eHc",
        "thumbnail": "https://i.ytimg.com/vi/w0rf4kB3eHc/maxresdefault.jpg",
        "published": "2026-09-22T00:53:59+00:00",
        "views": 13215,
        "channelName": "큰돌의터전",
        "channelId": "UCoN1XLeAX2OazuZdQ9b8U9Q",
        "channelAvatar": "https://yt3.googleusercontent.com/ZEzzfEVP7Ah2MxxMMcSodZsrzDEY_6o6czg9cnpzPZcZeffB28M3wZgssyQ-PR4qoA9c38Je=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=w0rf4kB3eHc"
    },
    {
        "title": "프리미어 자막 GPT 활용해서 빠르게 생성하는 꿀팁❤️ #편집하는여자 #프리미어 #gpt",
        "videoId": "jn8fBXaLZYo",
        "thumbnail": "https://i.ytimg.com/vi/jn8fBXaLZYo/maxresdefault.jpg",
        "published": "2026-09-25T04:00:31+00:00",
        "views": 21467,
        "channelName": "편집하는여자",
        "channelId": "UCa9OXODEH6azPrc_OEBM-Ew",
        "channelAvatar": "https://yt3.googleusercontent.com/NOn9_9EaoExT47fCEd-c7z4lOicB9nyQ-OiRcG4Gj6v_5JBkYDR8yJdHipr8hfyjlBZyXSgWT6I=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=jn8fBXaLZYo"
    },
    {
        "title": "한달에 팔리는 순대만 1500kg?! 아침마다 직접 만드는 43년 전통 수제 순대집 등. 맛있는 순대영상 몰아보기┃Korean Sundae/BEST3 KoreanStreetFood",
        "videoId": "SQEVD_aijlA",
        "thumbnail": "https://i.ytimg.com/vi/SQEVD_aijlA/maxresdefault.jpg",
        "published": "2026-09-30T12:30:22+00:00",
        "views": 35081,
        "channelName": "FoodieLand",
        "channelId": "UCHy8o-_zR_vHqpPN4uNUvkg",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_kOfhEDPOaS2FADqsqTIyXkxAIttSsCQBQiBpc36LFzSEM=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=SQEVD_aijlA"
    },
    {
        "title": "블렌더 3D 케이팝 데몬 헌터스 까치 만들기 | Blender K-POP DEMON HUNTERS Modeling",
        "videoId": "LfRXstxaRFA",
        "thumbnail": "https://i.ytimg.com/vi/LfRXstxaRFA/maxresdefault.jpg",
        "published": "2025-07-31T07:03:12+00:00",
        "views": 2155,
        "channelName": "하나리 hannahLee",
        "channelId": "UCX6G3PmhT4_Ku0DXRvlyNFA",
        "channelAvatar": "https://yt3.googleusercontent.com/PpphDLOM5Ly-5ZV4uAFDghqGv8ITvwI7cGnQ_0Taa70QH7vVJdaUCJk1-V1v3tSQMOEMMuqMOng=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=LfRXstxaRFA"
    },
    {
        "title": "세력이 약한 실내 벌통에 사는 벌들한테 증원 세력 2000마리 투입해보기(feat. 벌통 호흡기)",
        "videoId": "JsKL854CD1Y",
        "thumbnail": "https://i.ytimg.com/vi/JsKL854CD1Y/maxresdefault.jpg",
        "published": "2026-09-18T16:57:17+00:00",
        "views": 1652660,
        "channelName": "프응TV Honeybeefather",
        "channelId": "UCLJNGmEfcuugzEjLyZ6mKKw",
        "channelAvatar": "https://yt3.googleusercontent.com/Wk93tHGxlt6aMlHx6JfS7sf4Gc4Bi5JmAYR4XTuVmItM2sZAniz5c7T65QIX4k4k9k8yhBVKKA=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=JsKL854CD1Y"
    },
    {
        "title": "한칸만 내려가도 죽는 랜덤 중력 모드에서 드래곤 잡기",
        "videoId": "7pWQNwKL7IE",
        "thumbnail": "https://i.ytimg.com/vi/7pWQNwKL7IE/maxresdefault.jpg",
        "published": "2026-10-01T03:00:13+00:00",
        "views": 143484,
        "channelName": "휘용의 취미생활",
        "channelId": "UCtjBNJ4UbuWGLe-415urMOw",
        "channelAvatar": "https://yt3.googleusercontent.com/ytc/AIdro_mUJ08I6Aec4Zwz3596q7Vl20vC6FS1O0XuJPGoBfKNZw=s900-c-k-c0x00ffffff-no-rj",
        "url": "https://www.youtube.com/watch?v=7pWQNwKL7IE"
    }
];
